services:
  booking-service:
    image: ${DOCKER_REGISTRY-}booking-service
    build:
      context: .
      dockerfile: BookingService/Dockerfile
    depends_on:
      - booking-db
    ports:
      - "9090:9090"
    networks:
      - hotelio-net
  
  booking-history-service:
    image: ${DOCKER_REGISTRY-}booking-history-service
    build:
      context: .
      dockerfile: BookingHistoryService/Dockerfile
    ports:
      - "9091:9090"
    networks:
      - hotelio-net
      
  booking-db:
    image: postgres:15
    container_name: hotelio-booking-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5432:5432"
    volumes:
      - hotelio-booking-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

volumes:
  hotelio-booking-db-data:

networks:
  hotelio-net:
    external: true