appName: booking-service

image:
  name: hotelio-booking-service
  pullPolicy: Never 

# Конфигурация для обеих версий
versions:
  stable:
    tag: v1 
    replicas: 1
  canary:
    tag: v2 
    replicas: 1
  
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env: 

resources:
  limits:
    cpu: 200m   # 200 милли-ядер CPU
    memory: 256Mi # 256 мегабайт RAM
  requests:
    cpu: 100m
    memory: 128Mi
  
livenessProbe:
  path: /ping

readinessProbe:
  path: /ping
