version: "3.8"

services:
  tests:
    build:
      context: ./../../test
      dockerfile: Dockerfile
    container_name: hotelio-tests
    networks:
      - hotelio-net
    # depends_on:
      # - booking
    environment:
      DB_HOST: monolith-db # В Docker Compose имя сервиса 'db' является его хостом
      DB_USER: hotelio
      DB_PASSWORD: hotelio
      DB_NAME: hotelio
      DB_PORT: 5432
      API_URL: http://monolith:8080

  # booking:
  #   build:
  #     context: ./../../BookingService
  #     dockerfile: Dockerfile
  #   container_name: hotelio-booking
  #   ports:
  #     - "8080:9090"
  #   networks:
  #     - hotelio-net
  #   depends_on:
  #     - booking-db
  #   environment:
  #     DB_HOST: hotelio-booking-db # В Docker Compose имя сервиса 'db' является его хостом
  #     DB_USER: hotelio
  #     DB_PASSWORD: hotelio
  #     DB_NAME: hotelio
  #     DB_PORT: 5432
  #     Kafka:BootstrapServers: kafka:9092

  # booking-db:
  #   image: postgres:15
  #   container_name: hotelio-booking-db
  #   environment:
  #     POSTGRES_USER: hotelio
  #     POSTGRES_PASSWORD: hotelio
  #     POSTGRES_DB: hotelio
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - hotelio-booking-db-data:/var/lib/postgresql/data
  #   networks:
  #     - hotelio-net

volumes:
  hotelio-booking-db-data:

networks:
  hotelio-net:
    external: true
