{{- range $versionName, $versionConfig := .Values.versions }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.appName }}-{{ $versionName }}
  labels:
    app: {{ $.Values.appName }} 
    version: {{ $versionName }}
spec:
  replicas: {{ $versionConfig.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.appName }}
      version: {{ $versionName }}      
  template:
    metadata:
      labels:
        app: {{ $.Values.appName }}
        version: {{ $versionName }}
    spec:
      containers:
        - name: {{ $.Chart.Name }}-{{ $versionName }}
          image: "{{ $.Values.image.name }}:{{ $.Values.image.version }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}

          ports:
            - containerPort: {{ $.Values.service.targetPort }}

          env:
          {{- range $.Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
           - name: "APP_VERSION"
             value: "{{ $versionConfig.tag }}"
           - name: "ERROR_POSSIBLE"
             value: "{{ $versionConfig.isErrorPossible }}"

          livenessProbe:
            httpGet:
              path: {{ $.Values.livenessProbe.path }}
              port: {{ $.Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: {{ $.Values.readinessProbe.path }}
              port: {{ $.Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
---
{{- end }}