apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.appName }}-destination-rule
spec:
  host: {{ .Values.appName }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary

trafficPolicy:
  connectionPool:
    tcp:
      maxConnections: 100 # Максимум одновременных TCP-соединений к каждому поду
    http:
      http1MaxPendingRequests: 10 # Максимум  ожидающих HTTP/1.1 запросов в очереди
      maxRequestsPerConnection: 1 # Максимум запросов на соединение (для быстрой перебалансировки)
  outlierDetection:
    consecutive5xxErrors: 5 # После 5 последовательных 5xx ошибок
    interval: 30s           # Проверять каждые 30 секунд
    baseEjectionTime: 5m    # "Изгнать" (исключить из балансировки) проблемный под на 5 минут
    maxEjectionPercent: 50  # Исключить не более 50% подов одновременно

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-virtual-service
spec:
  hosts:
  - {{ .Values.appName }}
  http:
  - # --- ПРАВИЛО 1: Маршрут по фича-флагу (X-Feature-Enabled: true) ---
    match:
    - headers:
        X-Feature-Enabled:
          exact: "true" # Если заголовок X-Feature-Enabled равен "true"
    route:
    - destination:
        host: {{ .Values.appName }}
        subset: canary # Весь трафик идет на V2
      weight: 100

  - # --- ПРАВИЛО 2: Маршрут по умолчанию (Остальной трафик) ---
    route:
    - destination:
        host: {{ .Values.appName }}
        subset: stable # Весь остальной трафик идет на V1
      weight: 100

  # - route:
  #   - destination:
  #       host: {{ .Values.appName }}
  #       subset: stable
  #     weight: 90
  #   - destination:
  #       host: {{ .Values.appName }}
  #       subset: canary
  #     weight: 10

  retries:
    attempts: 3
    perTryTimeout: 2s
    retryOn: gateway-error, connect-failure, refused-stream, 5xx